service: ouroboros
org: nickhkraus

provider:
  name: aws
  runtime: python3.7
  stage: ${opt:stage, 'dev'}
  region: us-east-1

package:
 exclude:
   - ./**
 include:
   - ouroboros/ouroboros/**

functions:
  main:
    handler: ouroboros/ouroboros/main.handler
